### ISSUE TITLE
Question: Data Dupes between BSDR and DTCC

### ISSUE THREAD

**Issue by dado0583** [imanuelcostigan/dataonderivatives#26]
This isn't really an issue, more of a question. Do you need to dedupe transactions that may be reported to multiple SDRs? Have you given any thought about how to dedupe if so?

Nice work on putting this together. I've been scraping DTCC data and storing them in my own personal S3 on AWS. If you need an extract or something let me know. Thanks

**Comment by imanuelcostigan** [comment]
@dado0583 tbh, I am not sure. I haven't thought about this. If you work out the answer, let me know.

**Comment by hetzer-ltd** [comment]
Hi David,

I’m a student studying financial engineering and researching historical CFTC/DTCC SDR FX options data. In your 2017 comment you mentioned that you had been scraping DTCC data and storing it in a personal S3 bucket.

Do you happen to still have any of the archived FOREX end-of-day files, particularly data from 2013–2020? The original DTCC objects are now in Deep Archive and cannot be downloaded anonymously.

If you still retain the files, would you be willing to share a FOREX extract or make an archive available for research/study purposes? Even a limited date range would be very helpful.

Thank you.
