### ISSUE TITLE
DTCC URL scheme changes sometime in late November 

### ISSUE THREAD

**Issue by imanuelcostigan** [imanuelcostigan/dataonderivatives#33]
We see the following:
```r
ddr(lubridate::ymd(20201130), "IR")
#> # A tibble: 0 x 0
```

**Comment by landmann** [comment]
I see the same. What could it be now?

**Comment by DavideMagno** [comment]
The root link of the DTCC report has changed to "https://kgc0418-tdw-data2-0.s3.amazonaws.com/cftc/eod" while in the package it is still "https://kgc0418-tdw-data2-0.s3.amazonaws.com/slices". @imanuelcostigan can you please update it?
